// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ca.proto

/*
Package ca_grpc is a generated protocol buffer package.

It is generated from these files:
	ca.proto

It has these top-level messages:
	IsPermissionReply
	AddressRequest
	AddressReply
*/
package ca_grpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type IsPermissionReply struct {
	IsPermission bool `protobuf:"varint,1,opt,name=IsPermission" json:"IsPermission,omitempty"`
}

func (m *IsPermissionReply) Reset()                    { *m = IsPermissionReply{} }
func (m *IsPermissionReply) String() string            { return proto.CompactTextString(m) }
func (*IsPermissionReply) ProtoMessage()               {}
func (*IsPermissionReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *IsPermissionReply) GetIsPermission() bool {
	if m != nil {
		return m.IsPermission
	}
	return false
}

// The request message containing the user's name.
type AddressRequest struct {
	Addr string `protobuf:"bytes,1,opt,name=addr" json:"addr,omitempty"`
}

func (m *AddressRequest) Reset()                    { *m = AddressRequest{} }
func (m *AddressRequest) String() string            { return proto.CompactTextString(m) }
func (*AddressRequest) ProtoMessage()               {}
func (*AddressRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *AddressRequest) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

// The response message containing the greetings
type AddressReply struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *AddressReply) Reset()                    { *m = AddressReply{} }
func (m *AddressReply) String() string            { return proto.CompactTextString(m) }
func (*AddressReply) ProtoMessage()               {}
func (*AddressReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *AddressReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*IsPermissionReply)(nil), "ca_grpc.IsPermissionReply")
	proto.RegisterType((*AddressRequest)(nil), "ca_grpc.AddressRequest")
	proto.RegisterType((*AddressReply)(nil), "ca_grpc.AddressReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Greeter service

type GreeterClient interface {
	// Sends a greeting
	JudgeAddress(ctx context.Context, in *AddressRequest, opts ...grpc.CallOption) (*AddressReply, error)
	AuthorityCtrl(ctx context.Context, in *AddressRequest, opts ...grpc.CallOption) (*IsPermissionReply, error)
}

type greeterClient struct {
	cc *grpc.ClientConn
}

func NewGreeterClient(cc *grpc.ClientConn) GreeterClient {
	return &greeterClient{cc}
}

func (c *greeterClient) JudgeAddress(ctx context.Context, in *AddressRequest, opts ...grpc.CallOption) (*AddressReply, error) {
	out := new(AddressReply)
	err := grpc.Invoke(ctx, "/ca_grpc.Greeter/JudgeAddress", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) AuthorityCtrl(ctx context.Context, in *AddressRequest, opts ...grpc.CallOption) (*IsPermissionReply, error) {
	out := new(IsPermissionReply)
	err := grpc.Invoke(ctx, "/ca_grpc.Greeter/AuthorityCtrl", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Greeter service

type GreeterServer interface {
	// Sends a greeting
	JudgeAddress(context.Context, *AddressRequest) (*AddressReply, error)
	AuthorityCtrl(context.Context, *AddressRequest) (*IsPermissionReply, error)
}

func RegisterGreeterServer(s *grpc.Server, srv GreeterServer) {
	s.RegisterService(&_Greeter_serviceDesc, srv)
}

func _Greeter_JudgeAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).JudgeAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ca_grpc.Greeter/JudgeAddress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).JudgeAddress(ctx, req.(*AddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_AuthorityCtrl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).AuthorityCtrl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ca_grpc.Greeter/AuthorityCtrl",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).AuthorityCtrl(ctx, req.(*AddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Greeter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ca_grpc.Greeter",
	HandlerType: (*GreeterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "JudgeAddress",
			Handler:    _Greeter_JudgeAddress_Handler,
		},
		{
			MethodName: "AuthorityCtrl",
			Handler:    _Greeter_AuthorityCtrl_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ca.proto",
}

func init() { proto.RegisterFile("ca.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 221 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x48, 0x4e, 0xd4, 0x2b,
	0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4f, 0x4e, 0x8c, 0x4f, 0x2f, 0x2a, 0x48, 0x56, 0x32, 0xe7,
	0x12, 0xf4, 0x2c, 0x0e, 0x48, 0x2d, 0xca, 0xcd, 0x2c, 0x2e, 0xce, 0xcc, 0xcf, 0x0b, 0x4a, 0x2d,
	0xc8, 0xa9, 0x14, 0x52, 0xe2, 0xe2, 0x41, 0x16, 0x94, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x08, 0x42,
	0x11, 0x53, 0x52, 0xe1, 0xe2, 0x73, 0x4c, 0x49, 0x29, 0x4a, 0x2d, 0x2e, 0x0e, 0x4a, 0x2d, 0x2c,
	0x4d, 0x2d, 0x2e, 0x11, 0x12, 0xe2, 0x62, 0x49, 0x4c, 0x49, 0x29, 0x02, 0xab, 0xe6, 0x0c, 0x02,
	0xb3, 0x95, 0x34, 0xb8, 0x78, 0xe0, 0xaa, 0x40, 0x26, 0x4b, 0x70, 0xb1, 0xe7, 0xa6, 0x16, 0x17,
	0x27, 0xa6, 0xa7, 0x42, 0x95, 0xc1, 0xb8, 0x46, 0x93, 0x19, 0xb9, 0xd8, 0xdd, 0x8b, 0x52, 0x53,
	0x4b, 0x52, 0x8b, 0x84, 0x1c, 0xb8, 0x78, 0xbc, 0x4a, 0x53, 0xd2, 0x53, 0xa1, 0x5a, 0x85, 0xc4,
	0xf5, 0xa0, 0xce, 0xd5, 0x43, 0xb5, 0x52, 0x4a, 0x14, 0x53, 0xa2, 0x20, 0xa7, 0x52, 0x89, 0x41,
	0xc8, 0x8d, 0x8b, 0xd7, 0xb1, 0xb4, 0x24, 0x23, 0xbf, 0x28, 0xb3, 0xa4, 0xd2, 0xb9, 0xa4, 0x28,
	0x07, 0xb7, 0x11, 0x52, 0x70, 0x09, 0x8c, 0x70, 0x50, 0x62, 0x70, 0xe2, 0x5d, 0xc4, 0xc4, 0xe5,
	0xec, 0x18, 0xef, 0xe8, 0xe2, 0x12, 0xe4, 0x1a, 0x1c, 0x9c, 0xc4, 0x06, 0x0e, 0x3d, 0x63, 0x40,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x78, 0xfd, 0xeb, 0x3a, 0x49, 0x01, 0x00, 0x00,
}
